name: pylint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: pylint
      run: |
        sudo apt-get install pylint
        pylint ./src/hello.py
#        (date & pylint ./src/) >> ./pylint-log.txt
    
#    - name: git commands
#      run: |
#        git add .
#        git commit -m "pylint-log update"
#        git push
        
